# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ConversionDocument(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'base64': 'str',
        'file_extension': 'str',
        'file_name': 'str'
    }

    attribute_map = {
        'base64': 'base64',
        'file_extension': 'fileExtension',
        'file_name': 'fileName'
    }

    def __init__(self, base64=None, file_extension=None, file_name=None):  # noqa: E501
        """ConversionDocument - a model defined in Swagger"""  # noqa: E501

        self._base64 = None
        self._file_extension = None
        self._file_name = None
        self.discriminator = None

        if base64 is not None:
            self.base64 = base64
        if file_extension is not None:
            self.file_extension = file_extension
        if file_name is not None:
            self.file_name = file_name

    @property
    def base64(self):
        """Gets the base64 of this ConversionDocument.  # noqa: E501

          # noqa: E501

        :return: The base64 of this ConversionDocument.  # noqa: E501
        :rtype: str
        """
        return self._base64

    @base64.setter
    def base64(self, base64):
        """Sets the base64 of this ConversionDocument.

          # noqa: E501

        :param base64: The base64 of this ConversionDocument.  # noqa: E501
        :type: str
        """

        self._base64 = base64

    @property
    def file_extension(self):
        """Gets the file_extension of this ConversionDocument.  # noqa: E501

          # noqa: E501

        :return: The file_extension of this ConversionDocument.  # noqa: E501
        :rtype: str
        """
        return self._file_extension

    @file_extension.setter
    def file_extension(self, file_extension):
        """Sets the file_extension of this ConversionDocument.

          # noqa: E501

        :param file_extension: The file_extension of this ConversionDocument.  # noqa: E501
        :type: str
        """

        self._file_extension = file_extension

    @property
    def file_name(self):
        """Gets the file_name of this ConversionDocument.  # noqa: E501

          # noqa: E501

        :return: The file_name of this ConversionDocument.  # noqa: E501
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """Sets the file_name of this ConversionDocument.

          # noqa: E501

        :param file_name: The file_name of this ConversionDocument.  # noqa: E501
        :type: str
        """

        self._file_name = file_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConversionDocument, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConversionDocument):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
